import { useState, useEffect, useCallback } from 'react';
import { getProducts } from '../utils/api';
import { PURCHASE_MODES } from '../utils/constants';

// Sample products for development (when no API is available)
const SAMPLE_PRODUCTS = [
  {
    id: '1',
    name: 'Premium Tri-Ply Kadai 24cm',
    category: 'kadai',
    sku: 'BM-KD-001',
    image: '/images/categories/kadai.png',
    images: ['/images/categories/kadai.png', '/images/products/kadai-hero.png'],
    sizes: ['20cm', '22cm', '24cm', '26cm'],
    description: 'Professional-grade tri-ply stainless steel kadai with superior heat distribution and ergonomic handles. Perfect for deep-frying, curries, and everyday cooking.',
    features: ['18/10 Stainless Steel Interior', 'Aluminum Core for Even Heating', 'Riveted Ergonomic Handles', 'Induction & Gas Compatible', 'Dishwasher Safe'],
    price: 1299,
    mrp: 1999,
    purchaseMode: PURCHASE_MODES.ONLINE,
    isOnlinePurchase: true,
    isWholesaleOnly: false,
    amazonLink: '',
    stockStatus: 'in-stock',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Tri-Ply Fry Pan Classic',
    category: 'fry-pan',
    sku: 'BM-FP-001',
    image: '/images/categories/fry-pan.png',
    images: ['/images/categories/fry-pan.png', '/images/products/fry-pan-hero.png'],
    sizes: ['22cm', '24cm', '26cm'],
    description: 'Non-stick tri-ply fry pan perfect for everyday cooking. Even heat distribution ensures perfect results every time.',
    features: ['Non-Reactive Cooking Surface', 'Rapid & Even Heating', 'Cool-Touch Long Handle', 'Oven Safe up to 250°C', 'All Cooktop Compatible'],
    price: 1099,
    mrp: 1599,
    purchaseMode: PURCHASE_MODES.BOTH,
    isOnlinePurchase: true,
    isWholesaleOnly: false,
    amazonLink: 'https://amazon.in/example',
    stockStatus: 'in-stock',
    createdAt: '2026-01-02T00:00:00Z',
  },
  {
    id: '3',
    name: 'Stainless Steel Sauce Pan',
    category: 'sauce-pan',
    sku: 'BM-SP-001',
    image: '/images/categories/sauce-pan.png',
    images: ['/images/categories/sauce-pan.png', '/images/products/sauce-pan-hero.png'],
    sizes: ['16cm', '18cm'],
    description: 'Versatile sauce pan ideal for sauces, soups, and boiling. Features a comfortable cool-touch handle and tapered pour spout.',
    features: ['Tapered Pour Spout', 'Cool-Touch Handle', 'Tight-Fit Lid Included', 'Multi-Purpose Design', 'Easy to Clean'],
    price: 899,
    mrp: 1399,
    purchaseMode: PURCHASE_MODES.ONLINE,
    isOnlinePurchase: true,
    isWholesaleOnly: false,
    amazonLink: '',
    stockStatus: 'in-stock',
    createdAt: '2026-01-03T00:00:00Z',
  },
  {
    id: '4',
    name: 'Deep Cook Pot 26cm',
    category: 'cook-pots',
    sku: 'BM-CP-001',
    image: '/images/categories/cook-pots.png',
    images: ['/images/categories/cook-pots.png', '/images/products/cook-pots-hero.png'],
    sizes: ['22cm', '24cm', '26cm', '28cm'],
    description: 'Large capacity tri-ply cook pot for stews, biryanis, and bulk cooking. Heavy-duty construction with fully clad body.',
    features: ['Extra-Large Capacity', 'Fully Clad Tri-Ply Body', 'Heavy-Gauge Construction', 'All Cooktops Including Induction', 'Commercial Kitchen Grade'],
    price: 1599,
    mrp: 2499,
    purchaseMode: PURCHASE_MODES.WHOLESALE,
    isOnlinePurchase: false,
    isWholesaleOnly: true,
    amazonLink: '',
    stockStatus: 'in-stock',
    createdAt: '2026-01-04T00:00:00Z',
  },
  {
    id: '5',
    name: 'Professional Wok 30cm',
    category: 'wok',
    sku: 'BM-WK-001',
    image: '/images/categories/wok.png',
    images: ['/images/categories/wok.png', '/images/products/wok-hero.png'],
    sizes: ['28cm', '30cm', '32cm'],
    description: 'Restaurant-quality tri-ply wok with deep sides and flat bottom. Perfect for stir-frying and tossing.',
    features: ['High-Heat Performance', 'Flat Bottom for Stability', 'Deep Curved Walls', 'Professional Grade Build', 'Suitable for Commercial Use'],
    price: 1799,
    mrp: 2799,
    purchaseMode: PURCHASE_MODES.BOTH,
    isOnlinePurchase: true,
    isWholesaleOnly: false,
    amazonLink: 'https://amazon.in/example-wok',
    stockStatus: 'in-stock',
    createdAt: '2026-01-05T00:00:00Z',
  },
  {
    id: '6',
    name: 'Universal Lid Set',
    category: 'lids',
    sku: 'BM-LD-001',
    image: '/images/categories/lids.png',
    images: ['/images/categories/lids.png', '/images/products/lids-hero.png'],
    sizes: ['20cm', '22cm', '24cm', '26cm'],
    description: 'Tempered glass lids with stainless steel rim. Fits multiple cookware sizes with built-in steam vent.',
    features: ['Tempered Glass Construction', 'Stainless Steel Rim', 'Built-in Steam Vent', 'Heat-Resistant Knob', 'Universal Fit Design'],
    price: 499,
    mrp: 799,
    purchaseMode: PURCHASE_MODES.ONLINE,
    isOnlinePurchase: true,
    isWholesaleOnly: false,
    amazonLink: '',
    stockStatus: 'in-stock',
    createdAt: '2026-01-06T00:00:00Z',
  },
  {
    id: '7',
    name: 'Mini Tadka Pan',
    category: 'mini-series',
    sku: 'BM-MN-001',
    image: '/images/categories/mini-series.png',
    images: ['/images/categories/mini-series.png', '/images/products/mini-series-hero.png'],
    sizes: ['12cm', '14cm'],
    description: 'Compact tri-ply tadka pan for tempering spices. Premium build in a mini size — perfect for single servings.',
    features: ['Compact & Space-Saving', 'Perfect for Tadka/Tempering', 'Single Serving Size', 'Premium Tri-Ply Build', 'Long Handle for Safety'],
    price: 399,
    mrp: 649,
    purchaseMode: PURCHASE_MODES.ONLINE,
    isOnlinePurchase: true,
    isWholesaleOnly: false,
    amazonLink: '',
    stockStatus: 'in-stock',
    createdAt: '2026-01-07T00:00:00Z',
  },
  {
    id: '8',
    name: 'Tri-Ply Kadai Deep 28cm',
    category: 'kadai',
    sku: 'BM-KD-002',
    image: '/images/products/kadai-hero.png',
    images: ['/images/products/kadai-hero.png', '/images/categories/kadai.png'],
    sizes: ['24cm', '26cm', '28cm'],
    description: 'Extra-deep kadai for family-size cooking. Three-layer construction for even heat distribution across the entire surface.',
    features: ['Extra-Deep Design', 'Family-Size Capacity', 'Three-Layer Tri-Ply', 'Riveted Handles', 'All Cooktop Compatible'],
    price: 1899,
    mrp: 2999,
    purchaseMode: PURCHASE_MODES.BOTH,
    isOnlinePurchase: true,
    isWholesaleOnly: false,
    amazonLink: 'https://amazon.in/example-kadai',
    stockStatus: 'in-stock',
    createdAt: '2026-01-08T00:00:00Z',
  },
  {
    id: '9',
    name: 'Thermocolor Insulated Flask',
    category: 'bottle-flasks',
    sku: 'BM-BF-001',
    image: '/images/products/bottle-1.png',
    images: ['/images/products/bottle-1.png', '/images/products/bottle-flasks-hero.png'],
    sizes: ['750ml'],
    description: 'A sleek, premium double-wall insulated stainless steel water bottle. Dark brushed steel finish with subtle polished accents.',
    features: ['Double-Wall Vacuum Insulation', '24-Hour Temperature Retention', 'Food-Grade 304 Stainless Steel', 'Leak-Proof Cap', 'BPA Free'],
    price: 699,
    mrp: 1199,
    purchaseMode: PURCHASE_MODES.ONLINE,
    isOnlinePurchase: true,
    isWholesaleOnly: false,
    amazonLink: '',
    stockStatus: 'in-stock',
    createdAt: '2026-04-23T00:00:00Z',
  },
  {
    id: '10',
    name: 'Premium Coffee Thermal Flask',
    category: 'bottle-flasks',
    sku: 'BM-BF-002',
    image: '/images/products/bottle-2.png',
    images: ['/images/products/bottle-2.png', '/images/products/bottle-flasks-hero.png'],
    sizes: ['500ml'],
    description: 'A premium stainless steel thermal flask for coffee or tea. Matte black finish with a metallic cup lid.',
    features: ['Matte Black Premium Finish', 'Built-in Cup Lid', '12-Hour Hot Retention', 'Compact Travel Design', 'Anti-Slip Base'],
    price: 599,
    mrp: 999,
    purchaseMode: PURCHASE_MODES.BOTH,
    isOnlinePurchase: true,
    isWholesaleOnly: false,
    amazonLink: 'https://amazon.in/example-flask',
    stockStatus: 'in-stock',
    createdAt: '2026-04-23T00:00:00Z',
  },
  {
    id: '11',
    name: 'Heavy-Duty Sports Bottle',
    category: 'bottle-flasks',
    sku: 'BM-BF-003',
    image: '/images/products/bottle-3.png',
    images: ['/images/products/bottle-3.png', '/images/products/bottle-flasks-hero.png'],
    sizes: ['1000ml'],
    description: 'A large, heavy-duty stainless steel insulated sports water bottle. Silver metallic finish, perfect for active lifestyles.',
    features: ['1-Litre Large Capacity', 'Heavy-Duty Build', 'Wide Mouth Opening', 'Carabiner Clip Included', 'Sweat-Proof Exterior'],
    price: 849,
    mrp: 1399,
    purchaseMode: PURCHASE_MODES.WHOLESALE,
    isOnlinePurchase: false,
    isWholesaleOnly: true,
    amazonLink: '',
    stockStatus: 'in-stock',
    createdAt: '2026-04-23T00:00:00Z',
  },
];

const useProducts = () => {
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchProducts = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await getProducts();
      setProducts(data.products || data);
    } catch (err) {
      console.warn('API not available, using sample products:', err.message);
      setProducts(SAMPLE_PRODUCTS);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchProducts();
  }, [fetchProducts]);

  return { products, loading, error, refetch: fetchProducts };
};

export default useProducts;
